### ISSUE TITLE
你好面板出现问题了，

### ISSUE THREAD

**Issue by hackhy2020** [EmiyaTKK/Malio-Theme-for-SSPANEL#12]
我注册一个新号，他会跳转到其他用户页面，而且不购买套餐也可以使用！！！

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by EmiyaTKK** [comment]
这是你机场的问题吧？这里只是一个开源的项目，有问题去问你的机场主
