### ISSUE TITLE
[BUG] 无法正常登陆/创建账号(刚才手滑了,忘记填写详细内容)

### ISSUE THREAD

**Issue by AddictedCoins** [EmiyaTKK/Malio-Theme-for-SSPANEL#21]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
Vultr Silicon Valley的机器 2core 4G
CentOS SELinux 7 x64
PHP 7.4
MySQL 5.7.34
PHPMyAdmin 5.0

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
最新的commit

**Bug**
The bug information. 请描述你遇到的 Bug。
无法登陆

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
按照标准步骤完成安装后,无法登陆/创建账号,并且已经确认是100%按照步骤安装的

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
可以正常创建/登陆账号

**Comment by AddictedCoins** [comment]
访问的设备是MacBook Pro 16'' macOS Big Sur 11.2.3, 使用的是Safari

**Comment by EmiyaTKK** [comment]
请使用MySQL8.0

**Comment by AddictedCoins** [comment]
> 请使用MySQL8.0

谢谢回复,我现在就去试一下

**Comment by AddictedCoins** [comment]
还有一个问题我想向您问一下,就是那个首页语言选项的英国国旗emoji可否更改为美国国旗emoji?
