### ISSUE TITLE
[BUG]无法创建管理/普通账号

### ISSUE THREAD

**Issue by AddictedCoins** [EmiyaTKK/Malio-Theme-for-SSPANEL#22]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
CentOS 7.9.2009(Py3.7.9)
aaPanel 6.8.12(宝塔面板国际版)
Nginx 1.19.8
PHP-7.4
MySQL 8.0.24
phpmyAdmin 4.9

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
最新一个Commit/Latest Commit

**Bug**
The bug information. 请描述你遇到的 Bug。
无法创建任何账号

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
执行php xcat createAdmin 的时候报错

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
可以正常创建账户

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
(Terminal Log)
start create admin accountPHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'field list' in /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php:457
Stack trace:
#0 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(457): PDO->prepare()
#1 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run()
#4 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement()
#5 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#6 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Query/Builder.php(2107):  in /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php on line 729

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'field list' in /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php:457
Stack trace:
#0 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(457): PDO->prepare()
#1 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run()
#4 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement()
#5 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#6 /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Query/Builder.php(2107):  in /www/wwwroot/nucleuscloud.us/vendor/illuminate/database/Connection.php on line 729

**Comment by EmiyaTKK** [comment]
你是不是没导入数据库
"如果你是全新安装面板，请上传并导入网站目录下的 `/sql/glzjin_all.sql`、`/sql/malio_all.sql`"

**Comment by AddictedCoins** [comment]
> 你是不是没导入数据库
> "如果你是全新安装面板，请上传并导入网站目录下的 `/sql/glzjin_all.sql`、`/sql/malio_all.sql`"

我已经下载并导入网站目录下的 /sql/glzjin_all.sql、/sql/malio_all.sql文件至database里面了,可是aapanel在提醒我同时只能到入一个,如果再次导入的话会被overwrite

**Comment by EmiyaTKK** [comment]
两个都需要导入，不需要在乎那个提示

**Comment by AddictedCoins** [comment]
> 两个都需要导入，不需要在乎那个提示

麻烦了,感谢您的回复
